### ISSUE TITLE
Vector arrays

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#1329]
### Discussed in https://github.com/Alpine-DAV/ascent/discussions/1328

<div type='discussions-op-text'>

<sup>Originally posted by **yslan** July 10, 2024</sup>
Hi,

I wonder what's the proper way to pass a vector field to Ascent.

- 3 scalars   
  I know we can break it into scalars like this.
  ```
        mesh_data["fields/velocity_x/association"] = "vertex";
        mesh_data["fields/velocity_x/topology"] = "mesh";
        mesh_data["fields/velocity_x/values"].set_external((dfloat *)o_u.ptr(), N);
        
        mesh_data["fields/velocity_y/association"] = "vertex";
        mesh_data["fields/velocity_y/topology"] = "mesh";
        mesh_data["fields/velocity_y/values"].set_external((dfloat *)o_v.ptr(), N);
        
        mesh_data["fields/velocity_z/association"] = "vertex";
        mesh_data["fields/velocity_z/topology"] = "mesh";
        mesh_data["fields/velocity_z/values"].set_external((dfloat *)o_w.ptr(), N);        
  ```
  And, we can composite back to vector in `ascent_actions.yaml` 
  This approach is robust and well-tested in my code.

- vector   
  I've also managed to send the vector like this (Is this the correct way?).
  ```
        mesh_data["fields/velocity/association"] = "vertex";
        mesh_data["fields/velocity/topology"] = "mesh";
        mesh_data["fields/velocity/values/u"].set_external((dfloat *)o_u.ptr(), N);
        mesh_data["fields/velocity/values/v"].set_external((dfloat *)o_v.ptr(), N);
        mesh_data["fields/velocity/values/w"].set_external((dfloat *)o_w.ptr(), N);
  ```
  Then, from vector, it can extract components in `ascent_actions.yaml`

- Can we have both?   
  The question occurs when I have both vector and 3-scalars implementation with the same pointer.
  The idea is to keep "vector of arrays" structure, but also make sure both vector and scalar components are visible in ascent_actions.yaml, which saves a lots of conversion.
  This works when I run it on CPU backend but it gets SEGV when running with GPU. Both CPU and GPU are tested on Polaris.

I appreciate any suggestions.

Thanks,
Yu-Hsiang
 

</div>

**Comment by cyrush** [comment]
Second case (presented as a vector field directly) is crashing for GPU case.

**Comment by jfavre** [comment]
I guess I ran into this particular bug when attempting to validate my CUDA-enabled compilations using the provided test from  https://github.com/Alpine-DAV/ascent/pull/1370. This is a very valuable toy example, but it crashes on both of my installations (laptop with RTX CUDA 12.6) and Grace-Hopper nodes (CUDA 12.4). I managed to make the test pass by commenting out the  `device_move(data["fields/vel/values/?"])` and `device_cleanup(data["fields/vel/values/?"])` instructions. The "vel" data is not used anyway in the Ascent actions. Am curious as whether this test passes on a HIP device.

**Comment by jfavre** [comment]
I have done some debugging (using the latest git checkout) for the GPU case using the `t_ascent_gpu_data_source` test, which I had mentioned crashed for me when dealing with the "vel" field and found a solution. I have run
 `gdb /local/apps/Ascent-cuda/build/ascent-checkout/tests/ascent/t_ascent_gpu_data_source`
The trace is the following:

Thread 1 "t_ascent_gpu_da" received signal SIGSEGV, Segmentation fault.
0x00007fffe8e0c126 in void vtkm::exec::serial::internal::TaskTiling1DExecute<(anonymous namespace)::CopyWorklet const, vtkm::internal::Invocation<vtkm::internal::FunctionInterface<void (vtkm::internal::ArrayPortalRecombineVec<vtkm::internal::ArrayPortalMultiplexer<vtkm::internal::ArrayPortalStrideRead<double>, vtkm::internal::ArrayPortalStrideWrite<double> > >, vtkm::internal::ArrayPortalRecombineVec<vtkm::internal::ArrayPortalMultiplexer<vtkm::internal::ArrayPortalStrideRead<double>, vtkm::internal::ArrayPortalStrideWrite<double> > >)>, vtkm::internal::FunctionInterface<void (vtkm::worklet::WorkletMapField::FieldIn, vtkm::worklet::WorkletMapField::FieldOut)>, vtkm::internal::FunctionInterface<void (vtkm::placeholders::Arg<1>, vtkm::placeholders::Arg<2>)>, 1, vtkm::internal::ArrayPortalImplicit<vtkm::internal::IndexFunctor>, vtkm::internal::ArrayPortalImplicit<vtkm::cont::internal::ConstantFunctor<int> >, vtkm::internal::ArrayPortalImplicit<vtkm::internal::IndexFunctor>, vtkm::cont::DeviceAdapterTagSerial> const>(void*, void*, int, int) () from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
(gdb) where
#0  0x00007fffe8e0c126 in void vtkm::exec::serial::internal::TaskTiling1DExecute<(anonymous namespace)::CopyWorklet const, vtkm::internal::Invocation<vtkm::internal::FunctionInterface<void (vtkm::internal::ArrayPortalRecombineVec<vtkm::internal::ArrayPortalMultiplexer<vtkm::internal::ArrayPortalStrideRead<double>, vtkm::internal::ArrayPortalStrideWrite<double> > >, vtkm::internal::ArrayPortalRecombineVec<vtkm::internal::ArrayPortalMultiplexer<vtkm::internal::ArrayPortalStrideRead<double>, vtkm::internal::ArrayPortalStrideWrite<double> > >)>, vtkm::internal::FunctionInterface<void (vtkm::worklet::WorkletMapField::FieldIn, vtkm::worklet::WorkletMapField::FieldOut)>, vtkm::internal::FunctionInterface<void (vtkm::placeholders::Arg<1>, vtkm::placeholders::Arg<2>)>, 1, vtkm::internal::ArrayPortalImplicit<vtkm::internal::IndexFunctor>, vtkm::internal::ArrayPortalImplicit<vtkm::cont::internal::ConstantFunctor<int> >, vtkm::internal::ArrayPortalImplicit<vtkm::internal::IndexFunctor>, vtkm::cont::DeviceAdapterTagSerial> const>(void*, void*, int, int) () from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
#1  0x00007fffe93025e5 in vtkm::cont::DeviceAdapterAlgorithm<vtkm::cont::DeviceAdapterTagSerial>::ScheduleTask(vtkm::exec::serial::internal::TaskTiling1D&, int) ()
   from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
#2  0x00007fffe8e375ab in void vtkm::worklet::internal::DispatcherBase<vtkm::worklet::DispatcherMapField<(anonymous namespace)::CopyWorklet>, (anonymous namespace)::CopyWorklet, vtkm::worklet::WorkletMapField>::BasicInvoke<vtkm::internal::Invocation<vtkm::internal::FunctionInterface<void (vtkm::cont::ArrayHandleRecombineVec<double>, vtkm::cont::ArrayHandleRecombineVec<double>)>, vtkm::internal::FunctionInterface<void (vtkm::worklet::WorkletMapField::FieldIn, vtkm::worklet::WorkletMapField::FieldOut)>, vtkm::internal::FunctionInterface<void (vtkm::placeholders::Arg<1>, vtkm::placeholders::Arg<2>)>, 1, vtkm::internal::NullType, vtkm::internal::NullType, vtkm::internal::NullType, vtkm::internal::NullType> >(vtkm::internal::Invocation<vtkm::internal::FunctionInterface<void (vtkm::cont::ArrayHandleRecombineVec<double>, vtkm::cont::ArrayHandleRecombineVec<double>)>, vtkm::internal::FunctionInterface<void (vtkm::worklet::WorkletMapField::FieldIn, vtkm::worklet::WorkletMapField::FieldOut)>, vtkm::internal::FunctionInterface<void (vtkm::placeholders::Arg<1>, vtkm::placeholders::Arg<2>)>, 1, vtkm::internal::NullType, vtkm::internal::NullType, vtkm::internal::NullType, vtkm::internal::NullType>&, int) const () from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
#3  0x00007fffe8e37b75 in void (anonymous namespace)::UnknownCopyOnDevice::operator()<double, double>(vtkm::cont::DeviceAdapterId, vtkm::cont::ArrayHandleRecombineVec<double> const&, vtkm::cont::ArrayHandleRecombineVec<double> const&) () from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
#4  0x00007fffe8e3e3aa in (anonymous namespace)::DoUnknownArrayCopy(vtkm::cont::UnknownArrayHandle const&, vtkm::cont::UnknownArrayHandle const&) ()
   from /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/lib/libvtkm_cont-2.1.so.2.1
#5  0x00007ffff76f0b93 in vtkm::cont::detail::ArrayCopyImpl<std::integral_constant<bool, false> > (source=..., destination=...)
    at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:45
#6  0x00007ffff76e7688 in vtkm::cont::detail::ArrayCopyImpl<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> (source=..., destination=...)
    at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:70
#7  0x00007ffff76dd1a3 in vtkm::cont::ArrayCopy<vtkm::cont::UnknownArrayHandle, vtkm::cont::ArrayHandle<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> > (source=..., destination=...)
    at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:124
#8  0x00007ffff76fb538 in vtkm::cont::detail::ArrayCopyConcreteSrc<vtkm::cont::StorageTagSOA>::DoIt<vtkm::Vec<double, 3>, vtkm::cont::ArrayHandle<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> > (this=0x7fffffffa7a7, source=..., destination=...) at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:198
#9  0x00007ffff76f5f79 in vtkm::cont::detail::ArrayCopyConcreteSrc<vtkm::cont::StorageTagSOA>::operator()<vtkm::Vec<double, 3>, vtkm::cont::ArrayHandle<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> > (this=0x7fffffffa7a7, source=..., destination=...) at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:189
#10 0x00007ffff76eed4f in vtkm::cont::detail::ArrayCopyImpl<vtkm::Vec<double, 3>, vtkm::cont::StorageTagSOA, vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> (source=..., destination=...)
    at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:82
#11 0x00007ffff76e5b75 in vtkm::cont::ArrayCopy<vtkm::cont::ArrayHandleSOA<vtkm::Vec<double, 3> >, vtkm::cont::ArrayHandle<vtkm::Vec<double, 3>, vtkm::cont::StorageTagBasic> > (source=..., 
    destination=...) at /local/apps/Ascent-cuda/install/vtk-m-v2.1.0/include/vtkm-2.1/vtkm/cont/ArrayCopy.h:124
**#12 0x00007ffff76d8f42 in ascent::detail::ExtractVector<double> (dset=0x55555a51f800, u=..., v=..., w=..., num_vals=8000, dims=3, field_name="vel", assoc_str="vertex", topo_name="mesh", 
    zero_copy=true) at /local/apps/Ascent-cuda/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:511**
#13 0x00007ffff76c59e1 in ascent::VTKHDataAdapter::AddVectorField (field_name="vel", n_field=..., topo_name="mesh", neles=6859, nverts=8000, dset=0x55555a51f800, dims=3, zero_copy=true)
    at /local/apps/Ascent-cuda/ascent/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp:2183
#14 0x00007ffff76bd980 in ascent::VTKHDataAdapter::BlueprintToVTKmDataSet (node=..., zero_copy=true, topo_name_str="mesh")

something suspicious to me was the ExtractVector() call and I have found that if I comment out this single line

https://github.com/Alpine-DAV/ascent/blob/7c4d249aa4e586408112cf2ebed3431c9c11f6a7/src/libs/ascent/runtimes/ascent_vtkh_data_adapter.cpp#L510C1-L510C92

then the test runs successfully.
/local/apps/Ascent-cuda/build/ascent-checkout/tests/ascent/t_ascent_gpu_data_source
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ascent_gpu_data_source
[ RUN      ] ascent_gpu_data_source.test_gpu_source_contour_and_render_3d
[using ascent cuda support]
[WARNING: ascent lacks annotations (caliper) support]
[       OK ] ascent_gpu_data_source.test_gpu_source_contour_and_render_3d (2716 ms)
[----------] 1 test from ascent_gpu_data_source (2716 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2716 ms total)
[  PASSED  ] 1 test.

I leave it to a vtk-m expert, which I am not, to verify and test my idea.
